### PR TITLE
Farsi and RTL support

### PR DESCRIPTION
**Pull request by misafer**
dear volkan 
hope you well and be out of the politic and military games.
ive provided a rtl and farsi version at the moment. please check it and help me about.
thanks.

### CODE REVIEW

**Comment by volkanceylan** [comment]
Hi @misafer,

Thanks for the nice work. It says there are some conflicts so i can't merge it yet. I'll try to merge it manually this weekend.

If i understand it right, i should include rtl.css when a RTL language is selected right? Otherwise will it affect non-rtl language looks?

**Comment by misafer** [comment]
hi again, yes you're right. not just rtl.css but whole of SlickGrid at "Serene\Serene.Web\Scripts\SlickGrid".
i suggest to do like this
1- add a new field to languages table names "RTL" type of bit or bool
2- if this flag checks for current language then use rtl.css and second (RTL) version of slickgrid
god bless you

**Comment by misafer** [comment]
Dear Volkan
hi again. if you are out of time this week, i can help you with the process of rtl-ltr selection on language changes. may i ? and of course can get latest version of project and create a new pull request without these conflicts. is it ok ?
Thanks so

**Comment by volkanceylan** [comment]
No, thanks i'll try to merge manually today, if any problems i'll let you know.

**Comment by volkanceylan** [comment]
SlickGrid seems like has many changes, did you implement something yourself or used changes from geriamir branch?

**Comment by misafer** [comment]
i've change them at my own.

**Comment by volkanceylan** [comment]
I applied your changes but especially in slickgrid got a non-satisfying look, 

image

Are you sure this works fine on your side?

**Comment by volkanceylan** [comment]
Headers looks messed up

**Comment by volkanceylan** [comment]
@misafer i'm stuck atm, do you have a better view?

**Comment by misafer** [comment]
Yes. My version is OK. Where can I see your code?

**Comment by volkanceylan** [comment]
see rtl branch in Serene

**Comment by misafer** [comment]
hi dear. you missed this :
body{direction: rtl;}

**Comment by misafer** [comment]
put it at the head of rtl.css. everything gonna be ok.

**Comment by volkanceylan** [comment]
I tried that too but ok i'll have another look.

**Comment by misafer** [comment]
Hello Dear Volkan
hows going on. is it ok with the RTL css ?
im online at skype with my 'misafer@outlook.com' address.
after it i want to translate the serene GitBook too. help me with howtos.
Thanks

**Comment by volkanceylan** [comment]
Hi Misafer, I already integrated your changes to Serene. So just adding farsi language should be enough. For GitBook, i may get a copy of Serenity guide and give you write access so you can use GitBook to edit.

**Pull request closed without merging**
