### PR TITLE
Print header with date and time

### PR DESCRIPTION
**Pull request by Estrusco**
Hi @volkanceylan 
I have added a printHeader option for print the header of each page with date and time of report

### CODE REVIEW

**Comment by volkanceylan** [comment]
Thanks @Estrusco. Should we change it to something more clear like printDateTimeHeader etc?

**Comment by Estrusco** [comment]
Yes, of course

**Comment by Estrusco** [comment]
OK @volkanceylan I have done

**Comment by Estrusco** [comment]
@volkanceylan you can merge now?

**Comment by volkanceylan** [comment]
Thanks @Estrusco , sorry i forgot about this

**Pull request merged**
